name = "binance-funding-worker"
type = "javascript"

account_id = "patient-bush-441c"  # Twój account_id z Cloudflare
workers_dev = true
compatibility_date = "2025-03-26"

[build]
command = "npm install"
upload.format = "modules"
